[package]
name = "xlang_frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
colored = "3.0.0"
regex = "1.11.1"
unicode-segmentation = "1.12.0"
xlang_vm_core = {path = "../xlang_vm_core"}
