[package]
name = "XLang-Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
bincode = "1.3"
clap = { version = "4.5.32", features = ["derive"] }
