[package]
name = "xlang_vm_core"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bincode = "1.3"
colored = "3.0.0"
lazy_static = "1.5.0"
libloading = "0.8.6"
rustc-hash = "2.1.1"
serde = "1.0.219"
serde_json = "1.0.140"
unicode-segmentation = "1.12.0"
